const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#4F8EFF",
    background: "#F5F7FF",
    foreground: "#0D1117",
    card: "#FFFFFF",
    cardForeground: "#0D1117",
    primary: "#4F8EFF",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF1FF",
    secondaryForeground: "#1A2040",
    muted: "#EEF1FF",
    mutedForeground: "#6B7490",
    accent: "#7B5EFF",
    accentForeground: "#FFFFFF",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#E2E6F3",
    input: "#E2E6F3",
  },
  dark: {
    text: "#E8EAFF",
    tint: "#4F8EFF",
    background: "#080A12",
    foreground: "#E8EAFF",
    card: "#0F1120",
    cardForeground: "#E8EAFF",
    primary: "#4F8EFF",
    primaryForeground: "#FFFFFF",
    secondary: "#151828",
    secondaryForeground: "#9BA3C0",
    muted: "#151828",
    mutedForeground: "#6B7490",
    accent: "#7B5EFF",
    accentForeground: "#FFFFFF",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#1A1E35",
    input: "#1A1E35",
  },
  radius: 16,
};

export default colors;
