kind = "mobile"
previewPath = "/relateiq-production-build/"
title = "ConnectIQ"
version = "1.0.0"
id = "artifacts/connectiq"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/relateiq-production-build/" ]
localPort = 26183

[services.development]
run = "pnpm --filter @workspace/connectiq run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/connectiq", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/connectiq", "run", "serve" ]

[services.env]
PORT = "26183"
BASE_PATH = "/relateiq-production-build/"
