import { StyleSheet } from "react-native";

export const authColors = {
  background: "#080A12",
  card: "#0F1120",
  input: "#151828",
  border: "#1A1E35",
  text: "#E8EAFF",
  muted: "#6B7490",
  primary: "#4F8EFF",
  accent: "#7B5EFF",
  danger: "#FF4757",
};

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: authColors.background,
  },
  scroll: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 48,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 28,
  },
  brandBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  brandName: {
    color: authColors.text,
    fontSize: 26,
    fontWeight: "700",
    letterSpacing: -0.5,
    fontFamily: "Inter_700Bold",
  },
  title: {
    color: authColors.text,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: -0.4,
    textAlign: "center",
    fontFamily: "Inter_700Bold",
  },
  subtitle: {
    color: authColors.muted,
    fontSize: 14,
    textAlign: "center",
    marginTop: 6,
    marginBottom: 26,
    fontFamily: "Inter_400Regular",
  },
  label: {
    color: authColors.text,
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 7,
    marginTop: 14,
    fontFamily: "Inter_600SemiBold",
  },
  input: {
    backgroundColor: authColors.input,
    borderWidth: 1,
    borderColor: authColors.border,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: authColors.text,
    fontSize: 15,
    fontFamily: "Inter_400Regular",
  },
  inputError: {
    borderColor: authColors.danger,
  },
  error: {
    color: authColors.danger,
    fontSize: 12.5,
    marginTop: 6,
    fontFamily: "Inter_400Regular",
  },
  button: {
    backgroundColor: authColors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 22,
    flexDirection: "row",
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonPressed: {
    opacity: 0.85,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "Inter_700Bold",
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 22,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: authColors.border,
  },
  dividerText: {
    color: authColors.muted,
    fontSize: 12,
    marginHorizontal: 12,
    fontFamily: "Inter_500Medium",
  },
  socialButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: authColors.card,
    borderWidth: 1,
    borderColor: authColors.border,
    borderRadius: 14,
    paddingVertical: 15,
  },
  socialButtonText: {
    color: authColors.text,
    fontSize: 15,
    fontWeight: "600",
    marginLeft: 10,
    fontFamily: "Inter_600SemiBold",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 28,
  },
  footerText: {
    color: authColors.muted,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
  },
  footerLink: {
    color: authColors.primary,
    fontSize: 14,
    fontWeight: "700",
    fontFamily: "Inter_700Bold",
  },
});
